In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [7]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

## Ranges in a Array

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((2,4)) # omitint shape= gives same result in numpy

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operations

In [16]:
np.random.seed(101)

In [17]:
arr = np.random.randint(0,100,10)

In [18]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
arr2 = np.random.randint(0,100,10)

In [21]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [23]:
## Max Value
arr.max()

95

In [25]:
arr.argmax()

0

In [27]:
## Min Value
arr.min()

9

In [28]:
arr.argmin()

7

In [29]:
## Mean 
arr.mean()

60.8

In [31]:
## Reshape

#### Remember this must be reshaped to factor within the number of integers seeded.. 
#### i.e. .reshape(10,2) would not work since there is only 10 seed

arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [34]:
## Matrix 

mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
row = 0
col = 1

In [36]:
mat[row,col]

1

In [38]:
mat[3,2]

32

In [39]:
## Slicing

In [40]:
### Grab all items in column one
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
### Grab all items in row 2
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
mat[1,:].reshape(10,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [49]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [50]:
newmat = mat.copy()

In [51]:
newmat[0:3,0:4] = 0

In [52]:
newmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])